name: Deploy to rundgang.udk-berlin.de

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Sync files to remote host
        uses: up9cloud/action-rsync@v1.1
        env:
          HOST: rundgang.udk-berlin.de
          KEY: ${{secrets.SSH_RUNDGANG_UDK_BERLIN_DE}}
          TARGET: /opt/medienhaus-api/
          VERBOSE: true
          USER: root
          PORT: 22
          ARGS: --recursive --update --delete --compress --exclude=/.git/ --exclude=/config.js
          SSH_ARGS: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
          SOURCE: .
      - name: Restart medienhaus-cms-api service
        uses: fifsky/ssh-action@v0.0.5
        with:
          command: |
            cd /opt/medienhaus-api/
            npm clean-install
            systemctl restart medienhaus-api.service
          host: rundgang.udk-berlin.de
          user: root
          key: ${{secrets.SSH_RUNDGANG_UDK_BERLIN_DE}}
